[package]
name = "whisper-cli"
version = "0.1.0"
edition = "2021"
authors = ["afonsojramos"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.5", features = ["derive"] }
dirs = "5.0.1"
